spring.application.name=bankmanagement
spring.datasource.url=jdbc:postgresql://localhost:5432/bank_management
spring.datasource.username=bankuser
spring.datasource.password=bankpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true